config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, path: '/', only: %w[show new create] do
    resources :bookmarks, only: %w[new create]
    resources :reviews, only: %w[new create]
  end
  resources :bookmarks, only: %w[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: [:list]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates_uniqueness_of :name
  validates_presence_of :name
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates_uniqueness_of :title, :overview
  validates_presence_of :title, :overview
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %w[new create]
  before_action :set_bookmark, only: %w[destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    Bookmark.find(params[:id]).destroy
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %w[show]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params['list_id'])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li>
      <%= bookmark.comment %>
      <%= bookmark.list.name %>
      <%= bookmark.movie.title %>
      <%= link_to ('<i class="fa fa-trash"></i>').html_safe, bookmark, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </li>
  <% end %>
</ul>

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="mt-3 row col-8 m-auto">
      <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie %>
      <%= f.input :comment  %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path %>">
          <i class="fas fa-film"></i>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <a class="nav-link" href="<%= root_path %>">Home</a>
              </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dguvmuxdq/image/upload/v1653052428/hno1ogsibwneku91ji2t.jpg);">
      <div class="container">
        <h1>Save any kind of movies</h1>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="d-flex m-3 justify-content-end">
  <%= link_to 'Add a list', new_list_path, class: "btn btn-warning text-white" %>
</div>

<div class="row ">
  <% @lists.each do |list| %>
    <div class="col-12 col-sm-6 col-lg-4">
      <%= link_to list, class: "link" do %>
        <div class="card-category m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
        url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
          <h2><%= list.name %></h2>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="mt-3 row col-8 m-auto">
    <%= simple_form_for @list do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="d-flex m-3 justify-content-end">
  <%= link_to 'Go back', root_path, class: "me-3 btn btn-primary text-white" %>
  <%= link_to 'Add a Movie', new_list_bookmark_path(@list), class: "btn btn-warning text-white" %>
</div>
<h2 class="m-3"><%= @list.name %></h2>
<div class="container">
  <div class="row">
    <% @list.movies.each do |movie| %>
      <div class="col-12 col-sm-12 col-lg-6">
        <div class="card-product m-3">
          <img src="<%= movie.poster_url %>" />
          <div class="card-product-infos">
            <h2><%= movie.title %></h2>
            <p><strong><%= movie.bookmarks.find_by_list_id(@list.id).comment %></strong></p>
            <p><%= movie.overview %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<h2 class="m-3">What users think about this list</h2>
<div class="container">
  <div class="row">
    <% @list.reviews.each do |review| %>
      <div class="col-12">
        <div class="review mt-3">
          <p class="review-date"><small><%= review.created_at %></small></p>
          <div class="review-content">
            <p><%= review.content %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="d-flex m-3 justify-content-end">
  <%= link_to 'Post a Review', new_list_review_path(@list), class: "btn btn-secondary text-white" %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="mt-3 row justify-content-center">
    <div class="col-6">
        <%= simple_form_for [@list, @review] do |f| %>
        <%= f.input :content %>
        <%= f.submit class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>